version: '2'
services:
  web:
    #build: 
    #  context: .
    #  args:
    #    - https_proxy=$https_proxy
    image: docker.dev/kerasvis
    ports:
    - "5000"
    volumes:
    - ~/tmp/:/root/tmp/
    restart: always 
